apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-apex-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-apex
  template:
    metadata:
      labels:
        app: spring-boot-apex
    spec:
      containers:
        - name: spring-boot-apex
          image: mamatniroula1/apex-project
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-apexsvc
spec:
  selector:
    app: spring-boot-apex
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort